language: c

compiler:
  - clang
  - gcc

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq libzookeeper-mt-dev
  - curl -O https://dist.apache.org/repos/dist/release/kafka/kafka-0.8.0-beta1-src.tgz
  - tar xzf kafka-0.8.0-beta1-src.tgz
  - cd kafka-0.8.0-beta1-src
  - ./sbt update
  - ./sbt package
  - cd ..
  - sudo mv kafka-0.8.0-beta1-src.tgz /usr/local/kafka
  - screen -R zookeeper -d -m -L /usr/local/kafka/bin/zookeeper-server-start.sh /usr/local/kafka/config/zookeeper.properties
  - screen -R kafka -d -m -L /usr/local/kafka/bin/kafka-server-start.sh /usr/local/kafka/config/server.properties

script: ./autogen.sh && ./configure && make && make check