language: c

compiler:
  - clang
  - gcc

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq libzookeeper-mt-dev
  - curl -O https://dist.apache.org/repos/dist/release/kafka/kafka-0.8.0-beta1-src.tgz
  - tar xzf kafka-0.8.0-beta1-src.tgz
  - cd kafka-0.8.0-beta1-src
  - ./sbt update
  - ./sbt package
  - ./sbt assembly-package-dependency
  - nohup ./bin/zookeeper-server-start.sh ./config/zookeeper.properties &
  - nohup ./bin/kafka-server-start.sh ./config/server.properties &
  - ./bin/kafka-create-topic.sh --zookeeper localhost:2181 --topic test
  - cd ..

before_script:
  - ./autogen.sh
  - ./configure

script: make check